### ISSUE TITLE
Update the copyright holders in `LICENSE`

### ISSUE THREAD

**Issue by ItsDrike** [ItsDrike/code-jam-2024#21]
The `LICENSE` file should contain all of the contributors names and emails in the copyright / attribution section (just like those in pyproject.toml). Right now, it just says `Python Discord`, since that's a remnant from the original template repository owned by python discord.

**Comment by Paillat-dev** [comment]
License should too imo specify that it does not copyright the assets that are sent provided by thetvdb

**Comment by ItsDrike** [comment]
The license applies to all files in the code-base, it doesn't apply to the functionality / whatever is obtained from APIs and then shown to users. I think that the copyright footer on tvdb results is sufficient there. We don't have any of tvdb's copyrighted assets directly in the repo.

(Unless you count the swagger.yml, which can be gitignored anyways)

**Comment by Paillat-dev** [comment]
swagger.yml was entirely removed and is now pulled
