### ISSUE TITLE
Explain the bot's functionality / chosen topic in README

### ISSUE THREAD

**Issue by ItsDrike** [ItsDrike/code-jam-2024#26]
Add a section to the readme above the installation guide, that explains what our bot actually does. This can include some demonstration screenshots / video captures.

**Comment by dragonblz** [comment]
Im on it right now

**Comment by ItsDrike** [comment]
As discussed on discord, this one will still need to wait. This task will actually likely be one of the last tasks in the list, since it requires for all of the other commands to be implemented, so that we can take screenshots of the bot working and properly document the features that we added.

**Comment by ItsDrike** [comment]
Explained using a marp presentation.
