### ISSUE TITLE
Add utility methods to `ctx` by sublcassing it

### ISSUE THREAD

**Issue by Paillat-dev** [ItsDrike/code-jam-2024#36]
Add utility methods to ctx, for example `ctx.error` that allow to show an error (ex. a parameter is required when used in combination with another) while staying in theme with the other errors. Maybe it could even then be used inside of the `error_handler` ext. to send the errors.

For reference: 
- https://github.com/Pycord-Development/pycord/blob/master/examples/custom_context.py

**Comment by ItsDrike** [comment]
Slightly afraid what pyright will think here, it might cause issues, but if it'll work fine, it could be worth doing.
