### ISSUE TITLE
Capture the full traceback in error handler

### ISSUE THREAD

**Issue by ItsDrike** [ItsDrike/code-jam-2024#42]
Sometimes, the error message shown by the error handler is not sufficient to figure out where an issue occurred. This is because it only shows the error class and the message. It would be nice to add a button that could modify the embed / send another embed / do something else to show the entire traceback to the user.

Alternatively, maybe this button could even directly open a github link with the body pre-filled to contain this exception (these links look like this: <https://github.com/ItsDrike/code-jam-2024/issues/new?title=Issue%20Title&body=Issue%20Body>) or maybe the traceback could get uploaded somewhere automatically and the error embed can just show some reference number under which we can find it.

If it doesn't clutter the embed, we could even include it directly, but I think in most cases the traceback is just way too big for that to look visually good in the error embed.

**Comment by Paillat-dev** [comment]
Alternatively, as an attachment. Also, discord supports link buttons on mesages, which are persistent, and fairly easiy to use.
